export const FIELDS_BKP = ["nombre", "apellido", "edad"];
export const FIELDS = [
  "juzgadoCompetente",
  "ciudadJuzgado",
  "nombreDemandante",
  "nitDemandante",
  "domicilioDemandante",
  "representanteDemandante",
  "cedulaRepresentante",
  "abogado",
  "cedulaAbogado",
  "tpAbogado",
  "numeroDemandados",
  "nombreDemandado",
  "cedulaDemandado",
  "domicilioDemandado",
  "direccion",
  "correoElectronico",
  "idPagare",
  "importePagareLetras",
  "importePagareNumeros",
  "valorObligacionLetras",
  "valorObligacionNumeros",
  "fechaVencimiento",
  "interesCompensatorio",
  "valorInteresLetras",
  "valorInteresNumeros",
  "fechaInicialInteres",
  "fechaFinalInteres",
  "fechaAceleratoria",
  "cuantia",
  "direccionDemandante",
  "correoDemandante",
  "correoAbogado",
];

export const STATUS = {
  PENDING: "PENDING",
  DONE: "DONE",
  ERROR: "ERROR",
};
